#include "nc_keyboard.h"

const Str8 INPUT_DISPLAY_STR_TABLE[143] = {
    Str8Lit("Invalid Key"),
    Str8Lit("Escape"),
    Str8Lit("F1"),
    Str8Lit("F2"),
    Str8Lit("F3"),
    Str8Lit("F4"),
    Str8Lit("F5"),
    Str8Lit("F6"),
    Str8Lit("F7"),
    Str8Lit("F8"),
    Str8Lit("F9"),
    Str8Lit("F10"),
    Str8Lit("F11"),
    Str8Lit("F12"),
    Str8Lit("F13"),
    Str8Lit("F14"),
    Str8Lit("F15"),
    Str8Lit("F16"),
    Str8Lit("F17"),
    Str8Lit("F18"),
    Str8Lit("F19"),
    Str8Lit("F20"),
    Str8Lit("F21"),
    Str8Lit("F22"),
    Str8Lit("F23"),
    Str8Lit("F24"),
    Str8Lit("Tilde"),
    Str8Lit("0"),
    Str8Lit("1"),
    Str8Lit("2"),
    Str8Lit("3"),
    Str8Lit("4"),
    Str8Lit("5"),
    Str8Lit("6"),
    Str8Lit("7"),
    Str8Lit("8"),
    Str8Lit("9"),
    Str8Lit("Minus"),
    Str8Lit("Equal"),
    Str8Lit("Backspace"),
    Str8Lit("Tab"),
    Str8Lit("Q"),
    Str8Lit("W"),
    Str8Lit("E"),
    Str8Lit("R"),
    Str8Lit("T"),
    Str8Lit("Y"),
    Str8Lit("U"),
    Str8Lit("I"),
    Str8Lit("O"),
    Str8Lit("P"),
    Str8Lit("Left Bracket"),
    Str8Lit("Right Bracket"),
    Str8Lit("Back Slash"),
    Str8Lit("Caps Lock"),
    Str8Lit("A"),
    Str8Lit("S"),
    Str8Lit("D"),
    Str8Lit("F"),
    Str8Lit("G"),
    Str8Lit("H"),
    Str8Lit("J"),
    Str8Lit("K"),
    Str8Lit("L"),
    Str8Lit("Semicolon"),
    Str8Lit("Quote"),
    Str8Lit("Enter"),
    Str8Lit("Shift"),
    Str8Lit("Z"),
    Str8Lit("X"),
    Str8Lit("C"),
    Str8Lit("V"),
    Str8Lit("B"),
    Str8Lit("N"),
    Str8Lit("M"),
    Str8Lit("Comma"),
    Str8Lit("Full-Stop"),
    Str8Lit("Slash"),
    Str8Lit("Ctrl"),
    Str8Lit("Alt"),
    Str8Lit("Space"),
    Str8Lit("Menu"),
    Str8Lit("Scroll Lock"),
    Str8Lit("Pause"),
    Str8Lit("Insert"),
    Str8Lit("Home"),
    Str8Lit("Page Up"),
    Str8Lit("Delete"),
    Str8Lit("End"),
    Str8Lit("Page Down"),
    Str8Lit("Up"),
    Str8Lit("Left"),
    Str8Lit("Down"),
    Str8Lit("Right"),
    Str8Lit("Ex0"),
    Str8Lit("Ex1"),
    Str8Lit("Ex2"),
    Str8Lit("Ex3"),
    Str8Lit("Ex4"),
    Str8Lit("Ex5"),
    Str8Lit("Ex6"),
    Str8Lit("Ex7"),
    Str8Lit("Ex8"),
    Str8Lit("Ex9"),
    Str8Lit("Ex10"),
    Str8Lit("Ex11"),
    Str8Lit("Ex12"),
    Str8Lit("Ex13"),
    Str8Lit("Ex14"),
    Str8Lit("Ex15"),
    Str8Lit("Ex16"),
    Str8Lit("Ex17"),
    Str8Lit("Ex18"),
    Str8Lit("Ex19"),
    Str8Lit("Ex20"),
    Str8Lit("Ex21"),
    Str8Lit("Ex22"),
    Str8Lit("Ex23"),
    Str8Lit("Ex24"),
    Str8Lit("Ex25"),
    Str8Lit("Ex26"),
    Str8Lit("Ex27"),
    Str8Lit("Ex28"),
    Str8Lit("Ex29"),
    Str8Lit("Num Lock"),
    Str8Lit("Numpad Slash"),
    Str8Lit("Numpad Star"),
    Str8Lit("Numpad Minus"),
    Str8Lit("Numpad Plus"),
    Str8Lit("Numpad Full-Stop"),
    Str8Lit("Numpad 0"),
    Str8Lit("Numpad 1"),
    Str8Lit("Numpad 2"),
    Str8Lit("Numpad 3"),
    Str8Lit("Numpad 4"),
    Str8Lit("Numpad 5"),
    Str8Lit("Numpad 6"),
    Str8Lit("Numpad 7"),
    Str8Lit("Numpad 8"),
    Str8Lit("Numpad 9"),
    Str8Lit("Left Mouse Button"),
    Str8Lit("Middle Mouse Button"),
    Str8Lit("Right Mouse Button")
};
